# Generated by Django 3.2.3 on 2021-05-29 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minerva', '0002_auto_20210529_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale_Product',
            new_name='CartItem',
        ),
    ]
