# Generated by Django 3.2.3 on 2021-05-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerva', '0003_rename_sale_product_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='location',
            field=models.CharField(choices=[('OF', 'Oficina'), ('ML', 'Mercado Libre'), ('WS', 'Pagina Web'), ('IG', 'Instagram')], default='ML', max_length=2),
        ),
        migrations.AlterField(
            model_name='sale',
            name='state',
            field=models.CharField(choices=[('P', 'En proceso'), ('F', 'Concretado')], default='P', max_length=1),
        ),
    ]
