# Generated by Django 3.2.3 on 2021-05-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerva', '0004_auto_20210529_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='state',
            field=models.CharField(choices=[('PO', 'Pre-Venta'), ('PD', 'En proceso'), ('FI', 'Concretado')], default='PD', max_length=2),
        ),
    ]
